language: ruby

sudo: true

matrix:
  include:
    - os: osx
      osx_image: xcode10
      rvm: system
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
    - /usr/local/Homebrew/Library/Homebrew/vendor/bundle
    - /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby

install:
  - |
    # Force strict error checking.
    set -o errexit
    set -o pipefail
  - |
    # Switch to master branch.
    export HOMEBREW_COLOR=1
    export HOMEBREW_DEVELOPER=1
    export HOMEBREW_NO_AUTO_UPDATE=1
    brew update
  - |
    # Mirror the repo as a tap.
    TAP_DIR="$(brew --repository)/Library/Taps/${TRAVIS_REPO_SLUG}"
    mkdir -p "${TAP_DIR}"
    rsync -az --delete "${TRAVIS_BUILD_DIR}/" "${TAP_DIR}/"
    export TRAVIS_BUILD_DIR="${TAP_DIR}"
    builtin cd "${TRAVIS_BUILD_DIR}"

script: ./travis-ci.sh
# The reason why we do not simply run `brew cask ci` is because the task 
# will complain and fail if we do not remove all installed sub-packages during `uninstall`.
# However, we should not remove the sub-packages because they are the shared runtime between
# different versions and the other parallelly installed versions will fail to run if we 
# remove them.
# script: brew cask ci
