version: 2
jobs:
  update_sdk_versions:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.7-stretch-node-browsers-legacy

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run: 
          name: "Run script .."
          command: echo "Running circle ci ..."
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update_sdk_versions