version: 2
jobs:
  update_sdk_versions:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.7-stretch-node-browsers-legacy

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "0a:d3:a9:32:74:e2:32:24:08:c2:08:0d:c5:89:a8:45"

      - checkout

      - run: 
          name: "Run script .."
          command: echo "Running circle ci ..."
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update_sdk_versions